// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/binders/[id]" | "/binders/[id]/edit" | "/binders/new" | "/cards/[id]" | "/colecao/[username]" | "/collection" | "/configuracoes" | "/dashboard" | "/inicio" | "/login" | "/perfil" | "/perfil/[username]" | "/privacidade" | "/privacy" | "/termos" | "/terms";
type AppRouteHandlerRoutes = "/api/account" | "/api/binder" | "/api/binders" | "/api/binders/[id]" | "/api/binders/[id]/slots/[slotId]/assign" | "/api/cards" | "/api/cards/[id]" | "/api/cards/artists" | "/api/cards/expansions" | "/api/cards/ownership" | "/api/dashboard" | "/api/profile" | "/api/profile/[username]" | "/api/profile/[username]/artists" | "/api/profile/[username]/collection" | "/api/profile/[username]/expansions" | "/api/search" | "/api/settings" | "/auth/callback";
type PageRoutes = never;
type LayoutRoutes = "/";
type RedirectRoutes = "/dashboard";
type RewriteRoutes = never;
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes;

interface ParamMap {
    "/": {};
    "/api/account": {};
    "/api/binder": {};
    "/api/binders": {};
    "/api/binders/[id]": { id: string };
    "/api/binders/[id]/slots/[slotId]/assign": { id: string; slotId: string };
    "/api/cards": {};
    "/api/cards/[id]": { id: string };
    "/api/cards/artists": {};
    "/api/cards/expansions": {};
    "/api/cards/ownership": {};
    "/api/dashboard": {};
    "/api/profile": {};
    "/api/profile/[username]": { username: string };
    "/api/profile/[username]/artists": { username: string };
    "/api/profile/[username]/collection": { username: string };
    "/api/profile/[username]/expansions": { username: string };
    "/api/search": {};
    "/api/settings": {};
    "/auth/callback": {};
    "/binders/[id]": { id: string };
    "/binders/[id]/edit": { id: string };
    "/binders/new": {};
    "/cards/[id]": { id: string };
    "/colecao/[username]": { username: string };
    "/collection": {};
    "/configuracoes": {};
    "/dashboard": {};
    "/inicio": {};
    "/login": {};
    "/perfil": {};
    "/perfil/[username]": { username: string };
    "/privacidade": {};
    "/privacy": {};
    "/termos": {};
    "/terms": {};
}

export type ParamsOf<Route extends Routes> = ParamMap[Route];

interface LayoutSlotMap {
    "/": never;
}

export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes };

declare global {
    /**
     * Props for Next.js App Router page components
     * @example
     * ```tsx
     * export default function Page(props: PageProps<'/blog/[slug]'>) {
     *   const { slug } = await props.params
     *   return <div>Blog post: {slug}</div>
     * }
     * ```
     */
    interface PageProps<AppRoute extends AppRoutes> {
        params: Promise<ParamMap[AppRoute]>;
        searchParams: Promise<Record<string, string | string[] | undefined>>;
    }

    /**
     * Props for Next.js App Router layout components
     * @example
     * ```tsx
     * export default function Layout(props: LayoutProps<'/dashboard'>) {
     *   return <div>{props.children}</div>
     * }
     * ```
     */
    type LayoutProps<LayoutRoute extends LayoutRoutes> = {
        params: Promise<ParamMap[LayoutRoute]>;
        children: React.ReactNode;
    } & {
        [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode;
    };

    /**
     * Context for Next.js App Router route handlers
     * @example
     * ```tsx
     * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
     *   const { id } = await context.params
     *   return Response.json({ id })
     * }
     * ```
     */
    interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
        params: Promise<ParamMap[AppRouteHandlerRoute]>;
    }
}
