// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type { NextRequest } from "next/server.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
    default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
    generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
    generateMetadata?: (props: { params: Promise<ParamMap[Route]> } & any, parent: ResolvingMetadata) => Promise<any> | any;
    generateViewport?: (props: { params: Promise<ParamMap[Route]> } & any, parent: ResolvingViewport) => Promise<any> | any;
    metadata?: any;
    viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
    default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
    generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
    generateMetadata?: (props: { params: Promise<ParamMap[Route]> } & any, parent: ResolvingMetadata) => Promise<any> | any;
    generateViewport?: (props: { params: Promise<ParamMap[Route]> } & any, parent: ResolvingViewport) => Promise<any> | any;
    metadata?: any;
    viewport?: any;
};

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
    GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
    POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
    PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
    PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
    DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
    HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
    OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void;
};

// Validate ../../src/app/binders/[id]/edit/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/binders/[id]/edit">> = Specific;
    const handler = {} as typeof import("../../src/app/binders/[id]/edit/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/binders/[id]/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/binders/[id]">> = Specific;
    const handler = {} as typeof import("../../src/app/binders/[id]/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/binders/new/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/binders/new">> = Specific;
    const handler = {} as typeof import("../../src/app/binders/new/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/cards/[id]/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/cards/[id]">> = Specific;
    const handler = {} as typeof import("../../src/app/cards/[id]/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/colecao/[username]/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/colecao/[username]">> = Specific;
    const handler = {} as typeof import("../../src/app/colecao/[username]/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/collection/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/collection">> = Specific;
    const handler = {} as typeof import("../../src/app/collection/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/configuracoes/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/configuracoes">> = Specific;
    const handler = {} as typeof import("../../src/app/configuracoes/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/dashboard/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific;
    const handler = {} as typeof import("../../src/app/dashboard/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/inicio/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/inicio">> = Specific;
    const handler = {} as typeof import("../../src/app/inicio/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/login/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific;
    const handler = {} as typeof import("../../src/app/login/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
    const handler = {} as typeof import("../../src/app/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/perfil/[username]/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/perfil/[username]">> = Specific;
    const handler = {} as typeof import("../../src/app/perfil/[username]/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/perfil/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific;
    const handler = {} as typeof import("../../src/app/perfil/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/privacidade/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/privacidade">> = Specific;
    const handler = {} as typeof import("../../src/app/privacidade/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/privacy/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific;
    const handler = {} as typeof import("../../src/app/privacy/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/termos/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/termos">> = Specific;
    const handler = {} as typeof import("../../src/app/termos/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/terms/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific;
    const handler = {} as typeof import("../../src/app/terms/page.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/account/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/account">> = Specific;
    const handler = {} as typeof import("../../src/app/api/account/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/binder/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/binder">> = Specific;
    const handler = {} as typeof import("../../src/app/api/binder/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/binders/[id]/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/binders/[id]">> = Specific;
    const handler = {} as typeof import("../../src/app/api/binders/[id]/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/binders/[id]/slots/[slotId]/assign/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/binders/[id]/slots/[slotId]/assign">> = Specific;
    const handler = {} as typeof import("../../src/app/api/binders/[id]/slots/[slotId]/assign/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/binders/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/binders">> = Specific;
    const handler = {} as typeof import("../../src/app/api/binders/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/cards/[id]/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]">> = Specific;
    const handler = {} as typeof import("../../src/app/api/cards/[id]/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/cards/artists/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/artists">> = Specific;
    const handler = {} as typeof import("../../src/app/api/cards/artists/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/cards/expansions/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/expansions">> = Specific;
    const handler = {} as typeof import("../../src/app/api/cards/expansions/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/cards/ownership/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/ownership">> = Specific;
    const handler = {} as typeof import("../../src/app/api/cards/ownership/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/cards/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards">> = Specific;
    const handler = {} as typeof import("../../src/app/api/cards/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/dashboard/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific;
    const handler = {} as typeof import("../../src/app/api/dashboard/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/profile/[username]/artists/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[username]/artists">> = Specific;
    const handler = {} as typeof import("../../src/app/api/profile/[username]/artists/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/profile/[username]/collection/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[username]/collection">> = Specific;
    const handler = {} as typeof import("../../src/app/api/profile/[username]/collection/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/profile/[username]/expansions/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[username]/expansions">> = Specific;
    const handler = {} as typeof import("../../src/app/api/profile/[username]/expansions/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/profile/[username]/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[username]">> = Specific;
    const handler = {} as typeof import("../../src/app/api/profile/[username]/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/profile/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific;
    const handler = {} as typeof import("../../src/app/api/profile/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/search/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific;
    const handler = {} as typeof import("../../src/app/api/search/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/api/settings/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific;
    const handler = {} as typeof import("../../src/app/api/settings/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/auth/callback/route.ts
{
    type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific;
    const handler = {} as typeof import("../../src/app/auth/callback/route.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}

// Validate ../../src/app/layout.tsx
{
    type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
    const handler = {} as typeof import("../../src/app/layout.js");
    type __Check = __IsExpected<typeof handler>;
    // @ts-ignore
    type __Unused = __Check;
}
